package com.deptinfo.tp3.classes;

// Generated 2014-12-02 13:16:42 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * BiModespaiements generated by hbm2java
 */
public class BiModespaiements implements java.io.Serializable {

	private String modePaiementCd;
	private String cdDescFr;
	private String cdDescEn;
	private Set biEmpruntses = new HashSet(0);

	public BiModespaiements() {
	}

	public BiModespaiements(String modePaiementCd, String cdDescFr,
			String cdDescEn) {
		this.modePaiementCd = modePaiementCd;
		this.cdDescFr = cdDescFr;
		this.cdDescEn = cdDescEn;
	}

	public BiModespaiements(String modePaiementCd, String cdDescFr,
			String cdDescEn, Set biEmpruntses) {
		this.modePaiementCd = modePaiementCd;
		this.cdDescFr = cdDescFr;
		this.cdDescEn = cdDescEn;
		this.biEmpruntses = biEmpruntses;
	}

	public String getModePaiementCd() {
		return this.modePaiementCd;
	}

	public void setModePaiementCd(String modePaiementCd) {
		this.modePaiementCd = modePaiementCd;
	}

	public String getCdDescFr() {
		return this.cdDescFr;
	}

	public void setCdDescFr(String cdDescFr) {
		this.cdDescFr = cdDescFr;
	}

	public String getCdDescEn() {
		return this.cdDescEn;
	}

	public void setCdDescEn(String cdDescEn) {
		this.cdDescEn = cdDescEn;
	}

	public Set getBiEmpruntses() {
		return this.biEmpruntses;
	}

	public void setBiEmpruntses(Set biEmpruntses) {
		this.biEmpruntses = biEmpruntses;
	}

}
