package com.deptinfo.tp3.classes;

// Generated 2014-12-02 13:16:42 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * BiReservation generated by hbm2java
 */
public class BiReservation implements java.io.Serializable {

	private long idReservation;
	private int noMembre;
	private String noArticles;
	private Date dateReservation;

	public BiReservation() {
	}

	public BiReservation(long idReservation, int noMembre, String noArticles,
			Date dateReservation) {
		this.idReservation = idReservation;
		this.noMembre = noMembre;
		this.noArticles = noArticles;
		this.dateReservation = dateReservation;
	}

	public long getIdReservation() {
		return this.idReservation;
	}

	public void setIdReservation(long idReservation) {
		this.idReservation = idReservation;
	}

	public int getNoMembre() {
		return this.noMembre;
	}

	public void setNoMembre(int noMembre) {
		this.noMembre = noMembre;
	}

	public String getNoArticles() {
		return this.noArticles;
	}

	public void setNoArticles(String noArticles) {
		this.noArticles = noArticles;
	}

	public Date getDateReservation() {
		return this.dateReservation;
	}

	public void setDateReservation(Date dateReservation) {
		this.dateReservation = dateReservation;
	}

}
