package com.deptinfo.tp3.classes;

// Generated 2014-12-02 13:16:42 by Hibernate Tools 4.3.1

import java.math.BigDecimal;

/**
 * BiVentesproduits generated by hbm2java
 */
public class BiVentesproduits implements java.io.Serializable {

	private BiVentesproduitsId id;
	private char indicateurTaxable;
	private int qteAchetee;
	private BigDecimal prixUnitaire;
	private BigDecimal totalAchatProduit;

	public BiVentesproduits() {
	}

	public BiVentesproduits(BiVentesproduitsId id, char indicateurTaxable,
			int qteAchetee, BigDecimal prixUnitaire,
			BigDecimal totalAchatProduit) {
		this.id = id;
		this.indicateurTaxable = indicateurTaxable;
		this.qteAchetee = qteAchetee;
		this.prixUnitaire = prixUnitaire;
		this.totalAchatProduit = totalAchatProduit;
	}

	public BiVentesproduitsId getId() {
		return this.id;
	}

	public void setId(BiVentesproduitsId id) {
		this.id = id;
	}

	public char getIndicateurTaxable() {
		return this.indicateurTaxable;
	}

	public void setIndicateurTaxable(char indicateurTaxable) {
		this.indicateurTaxable = indicateurTaxable;
	}

	public int getQteAchetee() {
		return this.qteAchetee;
	}

	public void setQteAchetee(int qteAchetee) {
		this.qteAchetee = qteAchetee;
	}

	public BigDecimal getPrixUnitaire() {
		return this.prixUnitaire;
	}

	public void setPrixUnitaire(BigDecimal prixUnitaire) {
		this.prixUnitaire = prixUnitaire;
	}

	public BigDecimal getTotalAchatProduit() {
		return this.totalAchatProduit;
	}

	public void setTotalAchatProduit(BigDecimal totalAchatProduit) {
		this.totalAchatProduit = totalAchatProduit;
	}

}
