package com.deptinfo.tp3.classes;

// Generated 2014-12-02 13:16:42 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

/**
 * BiVentes generated by hbm2java
 */
public class BiVentes implements java.io.Serializable {

	private int venteId;
	private int noMembre;
	private String modePaiementCd;
	private Date dateVente;
	private BigDecimal totalVente;
	private BigDecimal taxeProvCourante;
	private BigDecimal taxeFedCourante;
	private BigDecimal totalTaxes;
	private BigDecimal grandTotalVente;

	public BiVentes() {
	}

	public BiVentes(int venteId, int noMembre, String modePaiementCd,
			Date dateVente, BigDecimal totalVente) {
		this.venteId = venteId;
		this.noMembre = noMembre;
		this.modePaiementCd = modePaiementCd;
		this.dateVente = dateVente;
		this.totalVente = totalVente;
	}

	public BiVentes(int venteId, int noMembre, String modePaiementCd,
			Date dateVente, BigDecimal totalVente, BigDecimal taxeProvCourante,
			BigDecimal taxeFedCourante, BigDecimal totalTaxes,
			BigDecimal grandTotalVente) {
		this.venteId = venteId;
		this.noMembre = noMembre;
		this.modePaiementCd = modePaiementCd;
		this.dateVente = dateVente;
		this.totalVente = totalVente;
		this.taxeProvCourante = taxeProvCourante;
		this.taxeFedCourante = taxeFedCourante;
		this.totalTaxes = totalTaxes;
		this.grandTotalVente = grandTotalVente;
	}

	public int getVenteId() {
		return this.venteId;
	}

	public void setVenteId(int venteId) {
		this.venteId = venteId;
	}

	public int getNoMembre() {
		return this.noMembre;
	}

	public void setNoMembre(int noMembre) {
		this.noMembre = noMembre;
	}

	public String getModePaiementCd() {
		return this.modePaiementCd;
	}

	public void setModePaiementCd(String modePaiementCd) {
		this.modePaiementCd = modePaiementCd;
	}

	public Date getDateVente() {
		return this.dateVente;
	}

	public void setDateVente(Date dateVente) {
		this.dateVente = dateVente;
	}

	public BigDecimal getTotalVente() {
		return this.totalVente;
	}

	public void setTotalVente(BigDecimal totalVente) {
		this.totalVente = totalVente;
	}

	public BigDecimal getTaxeProvCourante() {
		return this.taxeProvCourante;
	}

	public void setTaxeProvCourante(BigDecimal taxeProvCourante) {
		this.taxeProvCourante = taxeProvCourante;
	}

	public BigDecimal getTaxeFedCourante() {
		return this.taxeFedCourante;
	}

	public void setTaxeFedCourante(BigDecimal taxeFedCourante) {
		this.taxeFedCourante = taxeFedCourante;
	}

	public BigDecimal getTotalTaxes() {
		return this.totalTaxes;
	}

	public void setTotalTaxes(BigDecimal totalTaxes) {
		this.totalTaxes = totalTaxes;
	}

	public BigDecimal getGrandTotalVente() {
		return this.grandTotalVente;
	}

	public void setGrandTotalVente(BigDecimal grandTotalVente) {
		this.grandTotalVente = grandTotalVente;
	}

}
